{% set version = "0.3.1" %}

package:
  name: quspin-openmp
  version: {{ version }}

source:
  url: https://github.com/weinbe58/QuSpin/archive/dev_{{ version }}.zip


build:
  number: 0
  script: python setup.py install --omp


requirements:
  build:
    - {{compiler('cxx')}}

  host:
    - llvm-openmp # [osx]
    - python {{ python }}
    - numpy 1.10.*
 
  run:
    - llvm-openmp # [osx]
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.0
    - six
    - joblib
    - dill
    - gmpy2 
    - numba
    
test:
  imports:
    - quspin 

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
