{% set version = "0.3.1" %}

package:
  name: quspin
  version: {{ version }}

source:
  url: https://github.com/weinbe58/QuSpin/archive/dev_{{ version }}.zip

build:
  script: $PYTHON setup.py install --omp

requirements:
  build:
    - python {{ python }}
    - {{compiler('cxx')}}

  host:
    - numpy 1.10.*
 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19.0
    - six
    - joblib
    - dill
    - gmpy2 
    - numba
    
test:
  imports:
    - quspin 

about:
  home: https://github.com/weinbe58/QuSpin.git
  license: BSD-3
